### ISSUE TITLE
error when trying to run

### ISSUE THREAD

**Issue by rosspower** [FlorianPommerening/FingerJoints#11]
Callback method failed

Stack trace:
Traceback (most recent call last):
  File "C:/Users/pcs/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/FingerJoints\commands.py", line 18, in notify
    self.callback(args)
  File "C:/Users/pcs/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/FingerJoints\commands.py", line 103, in _onCreate
    running_command = self.RUNNING_CREATE_COMMAND_CLASS(args)
  File "C:/Users/pcs/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/FingerJoints/FingerJoints.py", line 47, in __init__
    self.ui = ui.FingerJointUI(args.command.commandInputs, defaults)
  File "C:/Users/pcs/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/FingerJoints\ui.py", line 74, in __init__
    self._inputFixedNotchSize = inputs.addValueInput('inputFixedNotchSize', 'Notch Size', defaultUnit, defaultNotchSize)
  File "C:/Users/pcs/AppData/Local/Autodesk/webdeploy/production/1a27f23c10bc87f7eab1f89e440a46f886b5f544/Api/Python/packages\adsk\core.py", line 6052, in addValueInput
    return _core.CommandInputs_addValueInput(self, id, name, unitType, initialValue)
RuntimeError: 2 : InternalValidationError : input->evaluateStringAndUpdateUI(xlVal->valueAsIString(), dTemp, bValueStrChanged)

**Comment by FlorianPommerening** [comment]
Hmm, I have a suspicion of what this might be. Does the error occur every time you create a new joint? If so, can you try deleting the file `C:/Users/pcs/AppData/Roaming/Autodesk/Autodesk Fusion 360/API/AddIns/FingerJoints/defaults.json`?

The idea is that the dialog should always show you the last settings you use, so if you create multiple joints, you don't have to set up the same values every time. Now if you use a a variable in one design and then open the dialog in a design where this variable doesn't exist, this could potentially lead to an error like this.

**Comment by FlorianPommerening** [comment]
Release v1.3 fixes the issue I had in mind (https://github.com/FlorianPommerening/FingerJoints/releases). Please try again with this version. I'm closing this issue for now but if the error reoccurs, feel free to reopen it.
